"""Initial baseline

Revision ID: 00da28cc46d7
Revises: 
Create Date: 2026-07-12 16:04:17.090782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00da28cc46d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('SHIPPER', 'BROKER', 'CARRIER', 'OWNER_OPERATOR', name='companytype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='verificationstatus'), nullable=True),
    sa.Column('dot_number', sa.String(), nullable=True),
    sa.Column('mc_number', sa.String(), nullable=True),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('insurance_expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dot_number'),
    sa.UniqueConstraint('mc_number'),
    sa.UniqueConstraint('tax_id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('carrier_profiles',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('fleet_size', sa.Integer(), nullable=True),
    sa.Column('equipment_types', sa.JSON(), nullable=True),
    sa.Column('operating_regions', sa.JSON(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('company_vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('truck_number', sa.String(), nullable=True),
    sa.Column('trailer_number', sa.String(), nullable=True),
    sa.Column('equipment_type', sa.String(), nullable=True),
    sa.Column('capacity_lbs', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('registration_expiry', sa.Date(), nullable=True),
    sa.Column('maintenance_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('compliance_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('INSURANCE_LIABILITY', 'INSURANCE_CARGO', 'FMCSA_AUTHORITY', 'DOT_REGISTRATION', 'DRIVER_LICENSE', name='compliancetype'), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('VALID', 'EXPIRED', 'PENDING_VERIFICATION', 'REJECTED', name='compliancestatus'), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edi_configurations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('partner_id', sa.String(), nullable=True),
    sa.Column('isa_sender_id', sa.String(), nullable=False),
    sa.Column('isa_receiver_id', sa.String(), nullable=False),
    sa.Column('qualifier', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('invitations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_token'), ['token'], unique=True)

    op.create_table('loads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shipper_id', sa.String(), nullable=False),
    sa.Column('origin_address', sa.String(), nullable=False),
    sa.Column('destination_address', sa.String(), nullable=False),
    sa.Column('pickup_date', sa.DateTime(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=False),
    sa.Column('weight_lbs', sa.Integer(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=True),
    sa.Column('dimensions', sa.String(), nullable=True),
    sa.Column('special_instructions', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN_FOR_BIDDING', 'TENDER_SENT', 'TENDER_ACCEPTED', 'DRIVER_ASSIGNED', 'PICKUP_COMPLETED', 'IN_TRANSIT', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'DISPUTED', name='loadstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shipper_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loads_shipper_id'), ['shipper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loads_status'), ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', name='notificationtype'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)

    op.create_table('transportation_partnerships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('broker_company_id', sa.String(), nullable=False),
    sa.Column('partner_company_id', sa.String(), nullable=False),
    sa.Column('partner_type', sa.Enum('SHIPPER', 'BROKER', 'CARRIER', 'OWNER_OPERATOR', name='companytype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONNECTED', 'REJECTED', 'BLOCKED', 'REMOVED', 'CANCELLED', name='partnershipstatus'), nullable=False),
    sa.Column('request_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['broker_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['partner_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_company_id', 'partner_company_id', name='uq_broker_partner_partnership')
    )
    with op.batch_alter_table('transportation_partnerships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transportation_partnerships_broker_company_id'), ['broker_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transportation_partnerships_partner_company_id'), ['partner_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transportation_partnerships_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('requires_password_change', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('webhooks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'FAILED', name='webhookstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('admin_user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_entity_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_entity_id'), ['target_entity_id'], unique=False)

    op.create_table('bids',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('load_id', sa.String(), nullable=False),
    sa.Column('carrier_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'TENDER_SENT', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'EXPIRED', 'NOT_SELECTED', name='bidstatus'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('available_pickup_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transit_time_estimate_hours', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bids_carrier_id'), ['carrier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bids_load_id'), ['load_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bids_status'), ['status'], unique=False)

    op.create_table('company_users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'company_id')
    )
    op.create_table('disputes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('load_id', sa.String(), nullable=False),
    sa.Column('raised_by_company_id', sa.String(), nullable=False),
    sa.Column('against_company_id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED', name='disputestatus'), nullable=True),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['against_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.ForeignKeyConstraint(['raised_by_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disputes_against_company_id'), ['against_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_load_id'), ['load_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_raised_by_company_id'), ['raised_by_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_status'), ['status'], unique=False)

    op.create_table('driver_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('license_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emergency_contact', sa.String(), nullable=True),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', 'ON_TRIP', 'OFF_DUTY', 'ON_LEAVE', 'SUSPENDED', name='driverstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('load_id', sa.String(), nullable=False),
    sa.Column('reviewer_company_id', sa.String(), nullable=False),
    sa.Column('reviewee_company_id', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.ForeignKeyConstraint(['reviewee_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['reviewer_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('load_id', 'reviewer_company_id', name='uq_rating_load_reviewer')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_load_id'), ['load_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_reviewee_company_id'), ['reviewee_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_reviewer_company_id'), ['reviewer_company_id'], unique=False)

    op.create_table('shipments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('load_id', sa.String(), nullable=False),
    sa.Column('carrier_id', sa.String(), nullable=False),
    sa.Column('broker_id', sa.String(), nullable=True),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('driver_phone', sa.String(), nullable=True),
    sa.Column('truck_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('WAITING_FOR_DRIVER_ASSIGNMENT', 'DRIVER_ASSIGNED', 'DRIVER_ACCEPTED', 'PICKUP_STARTED', 'PICKUP_COMPLETED', 'IN_TRANSIT', 'DELIVERED', 'POD_UPLOADED', 'COMPLETED', 'DISPUTED', name='shipmentstatus'), nullable=True),
    sa.Column('current_location', sa.String(), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delay_reason', sa.String(), nullable=True),
    sa.Column('bol_url', sa.String(), nullable=True),
    sa.Column('pod_url', sa.String(), nullable=True),
    sa.Column('receiver_name', sa.String(), nullable=True),
    sa.Column('receiver_signature_url', sa.String(), nullable=True),
    sa.Column('delivery_notes', sa.String(), nullable=True),
    sa.Column('delivery_photos_urls', sa.String(), nullable=True),
    sa.Column('osd_reported', sa.Boolean(), nullable=True),
    sa.Column('osd_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['carrier_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_broker_id'), ['broker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_carrier_id'), ['carrier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_load_id'), ['load_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_shipments_status'), ['status'], unique=False)

    op.create_table('driver_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shipment_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('assigned_by', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='driverassignmentstatus'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_assignments_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_assignments_shipment_id'), ['shipment_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('shipper_id', sa.String(), nullable=False),
    sa.Column('shipment_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PAID', 'OVERDUE', 'VOID', name='invoicestatus'), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['shipper_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=True)

    op.create_table('partner_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shipment_id', sa.String(), nullable=False),
    sa.Column('broker_id', sa.String(), nullable=False),
    sa.Column('partner_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='assignmentstatus'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_assignments_shipment_id'), ['shipment_id'], unique=False)

    op.create_table('settlements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('carrier_id', sa.String(), nullable=False),
    sa.Column('shipment_id', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PAID', 'DISPUTED', name='settlementstatus'), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shipment_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'VERIFIED', 'REJECTED', name='documentstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_documents_shipment_id'), ['shipment_id'], unique=False)

    op.create_table('tenders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('load_id', sa.String(), nullable=False),
    sa.Column('shipper_id', sa.String(), nullable=False),
    sa.Column('carrier_id', sa.String(), nullable=False),
    sa.Column('bid_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED', name='tenderstatus'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['carrier_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.ForeignKeyConstraint(['shipper_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenders_carrier_id'), ['carrier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_load_id'), ['load_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_shipper_id'), ['shipper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_status'), ['status'], unique=False)

    op.create_table('settlement_line_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('settlement_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlement_line_items')
    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenders_status'))
        batch_op.drop_index(batch_op.f('ix_tenders_shipper_id'))
        batch_op.drop_index(batch_op.f('ix_tenders_load_id'))
        batch_op.drop_index(batch_op.f('ix_tenders_carrier_id'))

    op.drop_table('tenders')
    with op.batch_alter_table('shipment_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_documents_shipment_id'))

    op.drop_table('shipment_documents')
    op.drop_table('settlements')
    with op.batch_alter_table('partner_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_assignments_shipment_id'))

    op.drop_table('partner_assignments')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))

    op.drop_table('invoices')
    with op.batch_alter_table('driver_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_assignments_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_driver_assignments_driver_id'))

    op.drop_table('driver_assignments')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_status'))
        batch_op.drop_index(batch_op.f('ix_shipments_load_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_carrier_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_broker_id'))

    op.drop_table('shipments')
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_reviewer_company_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_reviewee_company_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_load_id'))

    op.drop_table('ratings')
    op.drop_table('driver_profiles')
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disputes_status'))
        batch_op.drop_index(batch_op.f('ix_disputes_raised_by_company_id'))
        batch_op.drop_index(batch_op.f('ix_disputes_load_id'))
        batch_op.drop_index(batch_op.f('ix_disputes_against_company_id'))

    op.drop_table('disputes')
    op.drop_table('company_users')
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bids_status'))
        batch_op.drop_index(batch_op.f('ix_bids_load_id'))
        batch_op.drop_index(batch_op.f('ix_bids_carrier_id'))

    op.drop_table('bids')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_admin_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    op.drop_table('webhooks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('transportation_partnerships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transportation_partnerships_status'))
        batch_op.drop_index(batch_op.f('ix_transportation_partnerships_partner_company_id'))
        batch_op.drop_index(batch_op.f('ix_transportation_partnerships_broker_company_id'))

    op.drop_table('transportation_partnerships')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_company_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('loads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loads_status'))
        batch_op.drop_index(batch_op.f('ix_loads_shipper_id'))

    op.drop_table('loads')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_invitations_email'))

    op.drop_table('invitations')
    op.drop_table('financial_accounts')
    op.drop_table('edi_configurations')
    op.drop_table('compliance_records')
    op.drop_table('company_vehicles')
    op.drop_table('carrier_profiles')
    op.drop_table('api_keys')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_name'))

    op.drop_table('companies')
    # ### end Alembic commands ###
