"""add hos logs

Revision ID: 9a391678883f
Revises: f738649e2510
Create Date: 2026-07-20 11:07:03.417189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a391678883f'
down_revision: Union[str, Sequence[str], None] = 'f738649e2510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    with op.batch_alter_table('driver_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_hos_status', sa.Enum('OFF_DUTY', 'SLEEPER', 'DRIVING', 'ON_DUTY_NOT_DRIVING', name='hosstatus'), nullable=True))
        batch_op.add_column(sa.Column('hos_last_updated', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_driver_profiles_users_manager_id', 'users', ['manager_id'], ['id'])

    op.create_table('driver_hos_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OFF_DUTY', 'SLEEPER', 'DRIVING', 'ON_DUTY_NOT_DRIVING', name='hosstatus'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name='fk_driver_hos_logs_users_driver_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_hos_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_hos_logs_driver_id'), ['driver_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    with op.batch_alter_table('driver_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_driver_profiles_users_manager_id', type_='foreignkey')
        batch_op.drop_column('hos_last_updated')
        batch_op.drop_column('current_hos_status')

    with op.batch_alter_table('driver_hos_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_hos_logs_driver_id'))
    op.drop_table('driver_hos_logs')

    # ### end Alembic commands ###
