"""Add ShipmentTracking model

Revision ID: eb971093c90f
Revises: 2f9afbff1563
Create Date: 2026-07-13 16:09:32.194724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb971093c90f'
down_revision: Union[str, Sequence[str], None] = '2f9afbff1563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_events_aggregate_id'))
        batch_op.drop_index(batch_op.f('ix_domain_events_aggregate_type'))
        batch_op.drop_index(batch_op.f('ix_domain_events_event_type'))

    op.drop_table('domain_events')
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_events_event_id'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_processed'))

    op.drop_table('outbox_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=True),
    sa.Column('processed', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_events_processed'), ['processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_event_id'), ['event_id'], unique=False)

    op.create_table('domain_events',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('aggregate_type', sa.VARCHAR(), nullable=True),
    sa.Column('aggregate_id', sa.VARCHAR(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(), nullable=True),
    sa.Column('payload', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_events_aggregate_type'), ['aggregate_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_events_aggregate_id'), ['aggregate_id'], unique=False)

    # ### end Alembic commands ###
