"""Add appointment scheduling fields to loads

Revision ID: f738649e2510
Revises: eb971093c90f
Create Date: 2026-07-13 17:40:12.747104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f738649e2510'
down_revision: Union[str, Sequence[str], None] = 'eb971093c90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('loads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_appointment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pickup_appointment_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pickup_contact_person', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pickup_contact_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pickup_dock_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pickup_reference_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pickup_special_instructions', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('delivery_appointment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivery_appointment_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('delivery_contact_person', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('delivery_contact_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('delivery_dock_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('delivery_reference_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('delivery_special_instructions', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loads', schema=None) as batch_op:
        batch_op.drop_column('delivery_special_instructions')
        batch_op.drop_column('delivery_reference_number')
        batch_op.drop_column('delivery_dock_number')
        batch_op.drop_column('delivery_contact_number')
        batch_op.drop_column('delivery_contact_person')
        batch_op.drop_column('delivery_appointment_time')
        batch_op.drop_column('delivery_appointment_date')
        batch_op.drop_column('pickup_special_instructions')
        batch_op.drop_column('pickup_reference_number')
        batch_op.drop_column('pickup_dock_number')
        batch_op.drop_column('pickup_contact_number')
        batch_op.drop_column('pickup_contact_person')
        batch_op.drop_column('pickup_appointment_time')
        batch_op.drop_column('pickup_appointment_date')



    # ### end Alembic commands ###
