"""Add missing indexes

Revision ID: fb3ca5eeb2b6
Revises: 00da28cc46d7
Create Date: 2026-07-12 16:11:17.713960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3ca5eeb2b6'
down_revision: Union[str, Sequence[str], None] = '00da28cc46d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_company_id'), ['company_id'], unique=False)

    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_users_role_id'), ['role_id'], unique=False)

    with op.batch_alter_table('company_vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_vehicles_status'), ['status'], unique=False)

    with op.batch_alter_table('compliance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_records_company_id'), ['company_id'], unique=False)

    with op.batch_alter_table('driver_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_assignments_assigned_by'), ['assigned_by'], unique=False)

    with op.batch_alter_table('edi_configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edi_configurations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edi_configurations_partner_id'), ['partner_id'], unique=False)

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_company_id'), ['company_id'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_shipper_id'), ['shipper_id'], unique=False)

    with op.batch_alter_table('partner_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_assignments_broker_id'), ['broker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_assignments_partner_id'), ['partner_id'], unique=False)

    with op.batch_alter_table('settlement_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlement_line_items_settlement_id'), ['settlement_id'], unique=False)

    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlements_carrier_id'), ['carrier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_shipment_id'), ['shipment_id'], unique=False)

    with op.batch_alter_table('shipment_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_documents_uploaded_by'), ['uploaded_by'], unique=False)

    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenders_bid_id'), ['bid_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)

    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhooks_company_id'), ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhooks_company_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_company_id'))

    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenders_bid_id'))

    with op.batch_alter_table('shipment_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_documents_uploaded_by'))

    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlements_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_settlements_carrier_id'))

    with op.batch_alter_table('settlement_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlement_line_items_settlement_id'))

    with op.batch_alter_table('partner_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_assignments_partner_id'))
        batch_op.drop_index(batch_op.f('ix_partner_assignments_broker_id'))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_shipper_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_shipment_id'))

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_company_id'))

    with op.batch_alter_table('edi_configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edi_configurations_partner_id'))
        batch_op.drop_index(batch_op.f('ix_edi_configurations_company_id'))

    with op.batch_alter_table('driver_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_assignments_assigned_by'))

    with op.batch_alter_table('compliance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_records_company_id'))

    with op.batch_alter_table('company_vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_vehicles_status'))

    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_users_role_id'))

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_company_id'))

    # ### end Alembic commands ###
